### ISSUE TITLE
fatal: Remote branch 2.4 not found in upstream origin

### ISSUE THREAD

**Issue by indiandragon** [mdegans/nano_build_opencv#7]
Hi,

Could not download 2.4 branch with the script.

with
`sudo ./build_opencv.sh 2.4`

**fatal: Remote branch 2.4 not found in upstream origin**

I have checked that the 2.4 branch exists.

**Comment by mdegans** [comment]
The problem seems to be that opencv_contrib isn't available for that version. To fix it, please comment out the line:
```git clone --branch "$1" https://github.com/opencv/opencv_contrib.git```
in the git_source function.

I will change the script in the next version so that opencv_contrib will only be cloned if the version is >3.4  (but you are welcome to submit a pull request if you do it yourself :)
